### ISSUE TITLE
Create new Tag v1.2.7?

### ISSUE THREAD

**Issue by PATROMO** [thomasklein/mite.php#5]
@thomasklein can you create a new version/tag v1.2.7 from master?

**Comment by yolk** [comment]
Maybe I don't get it at the moment: but which commits are you missing in tag v1.2.6?

**Comment by PATROMO** [comment]
994960eb4d9fd42113733c48cffabcae80c3faa8 because I dont want use dev-master in my composer.json.

**Comment by yolk** [comment]
Sorry, missed it ...
I just added a new release/tag [v1.2.7](https://github.com/thomasklein/mite.php/tree/v1.2.7).
